
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 05 10:18:55 GMT-06:00 2025
//----------------------------------------------------

package codigo;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Jun 05 10:18:55 GMT-06:00 2025
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\042\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\021\012\000\002\021\002\000\002\003\011" +
    "\000\002\004\004\000\002\004\002\000\002\005\004\000" +
    "\002\005\004\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\006\004\000\002\006\006\000\002\007" +
    "\011\000\002\010\004\000\002\010\002\000\002\011\005" +
    "\000\002\012\005\000\002\012\005\000\002\012\003\000" +
    "\002\013\005\000\002\013\005\000\002\013\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\005\000\002\015" +
    "\011\000\002\015\015\000\002\016\005\000\002\017\011" +
    "\000\002\017\013\000\002\020\016" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\150\000\006\005\ufffd\032\004\001\002\000\004\031" +
    "\144\001\002\000\004\005\012\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\004\005\143\001" +
    "\002\000\004\002\uffff\001\002\000\006\025\014\027\013" +
    "\001\002\000\004\021\133\001\002\000\004\021\015\001" +
    "\002\000\004\022\016\001\002\000\004\023\017\001\002" +
    "\000\020\005\025\006\022\010\026\011\023\012\031\024" +
    "\ufffa\027\033\001\002\000\020\005\ufff6\006\ufff6\010\ufff6" +
    "\011\ufff6\012\ufff6\024\ufff6\027\ufff6\001\002\000\020\005" +
    "\ufff5\006\ufff5\010\ufff5\011\ufff5\012\ufff5\024\ufff5\027\ufff5" +
    "\001\002\000\004\021\121\001\002\000\004\021\113\001" +
    "\002\000\004\026\112\001\002\000\004\027\107\001\002" +
    "\000\004\023\077\001\002\000\020\005\025\006\022\010" +
    "\026\011\023\012\031\024\ufffa\027\033\001\002\000\004" +
    "\024\075\001\002\000\004\021\057\001\002\000\004\026" +
    "\056\001\002\000\004\013\035\001\002\000\020\005\ufff7" +
    "\006\ufff7\010\ufff7\011\ufff7\012\ufff7\024\ufff7\027\ufff7\001" +
    "\002\000\010\021\040\027\043\030\036\001\002\000\020" +
    "\014\uffe7\015\uffe7\016\uffe7\017\uffe7\020\uffe7\022\uffe7\026" +
    "\uffe7\001\002\000\020\014\uffe9\015\uffe9\016\uffe9\017\uffe9" +
    "\020\uffe9\022\uffe9\026\uffe9\001\002\000\010\021\040\027" +
    "\043\030\036\001\002\000\020\014\uffec\015\uffec\016\050" +
    "\017\047\020\uffec\022\uffec\026\uffec\001\002\000\012\014" +
    "\045\015\044\022\uffef\026\uffef\001\002\000\020\014\uffe8" +
    "\015\uffe8\016\uffe8\017\uffe8\020\uffe8\022\uffe8\026\uffe8\001" +
    "\002\000\010\021\040\027\043\030\036\001\002\000\010" +
    "\021\040\027\043\030\036\001\002\000\020\014\uffee\015" +
    "\uffee\016\050\017\047\020\uffee\022\uffee\026\uffee\001\002" +
    "\000\010\021\040\027\043\030\036\001\002\000\010\021" +
    "\040\027\043\030\036\001\002\000\020\014\uffeb\015\uffeb" +
    "\016\uffeb\017\uffeb\020\uffeb\022\uffeb\026\uffeb\001\002\000" +
    "\020\014\uffea\015\uffea\016\uffea\017\uffea\020\uffea\022\uffea" +
    "\026\uffea\001\002\000\020\014\uffed\015\uffed\016\050\017" +
    "\047\020\uffed\022\uffed\026\uffed\001\002\000\010\014\045" +
    "\015\044\022\055\001\002\000\020\014\uffe6\015\uffe6\016" +
    "\uffe6\017\uffe6\020\uffe6\022\uffe6\026\uffe6\001\002\000\020" +
    "\005\ufff8\006\ufff8\010\ufff8\011\ufff8\012\ufff8\024\ufff8\027" +
    "\ufff8\001\002\000\004\005\060\001\002\000\004\027\033" +
    "\001\002\000\004\026\062\001\002\000\010\021\040\027" +
    "\043\030\036\001\002\000\004\026\067\001\002\000\010" +
    "\014\045\015\044\020\065\001\002\000\010\021\040\027" +
    "\043\030\036\001\002\000\012\014\045\015\044\022\uffe3" +
    "\026\uffe3\001\002\000\004\027\033\001\002\000\004\022" +
    "\071\001\002\000\004\023\072\001\002\000\020\005\025" +
    "\006\022\010\026\011\023\012\031\024\ufffa\027\033\001" +
    "\002\000\004\024\074\001\002\000\020\005\uffe0\006\uffe0" +
    "\010\uffe0\011\uffe0\012\uffe0\024\uffe0\027\uffe0\001\002\000" +
    "\004\002\ufffc\001\002\000\004\024\ufffb\001\002\000\020" +
    "\005\025\006\022\010\026\011\023\012\031\024\ufffa\027" +
    "\033\001\002\000\004\024\101\001\002\000\004\011\102" +
    "\001\002\000\004\021\103\001\002\000\010\021\040\027" +
    "\043\030\036\001\002\000\004\022\105\001\002\000\004" +
    "\026\106\001\002\000\020\005\uffe1\006\uffe1\010\uffe1\011" +
    "\uffe1\012\uffe1\024\uffe1\027\uffe1\001\002\000\006\013\110" +
    "\026\ufff4\001\002\000\004\030\111\001\002\000\004\026" +
    "\ufff3\001\002\000\020\005\ufff9\006\ufff9\010\ufff9\011\ufff9" +
    "\012\ufff9\024\ufff9\027\ufff9\001\002\000\010\021\040\027" +
    "\043\030\036\001\002\000\004\022\115\001\002\000\004" +
    "\023\116\001\002\000\020\005\025\006\022\010\026\011" +
    "\023\012\031\024\ufffa\027\033\001\002\000\004\024\120" +
    "\001\002\000\020\005\uffe2\006\uffe2\010\uffe2\011\uffe2\012" +
    "\uffe2\024\uffe2\027\uffe2\001\002\000\010\021\040\027\043" +
    "\030\036\001\002\000\004\022\123\001\002\000\004\023" +
    "\124\001\002\000\020\005\025\006\022\010\026\011\023" +
    "\012\031\024\ufffa\027\033\001\002\000\004\024\126\001" +
    "\002\000\022\005\uffe5\006\uffe5\007\127\010\uffe5\011\uffe5" +
    "\012\uffe5\024\uffe5\027\uffe5\001\002\000\004\023\130\001" +
    "\002\000\020\005\025\006\022\010\026\011\023\012\031" +
    "\024\ufffa\027\033\001\002\000\004\024\132\001\002\000" +
    "\020\005\uffe4\006\uffe4\010\uffe4\011\uffe4\012\uffe4\024\uffe4" +
    "\027\uffe4\001\002\000\006\005\135\022\ufff0\001\002\000" +
    "\004\022\137\001\002\000\004\027\136\001\002\000\004" +
    "\022\ufff1\001\002\000\004\023\140\001\002\000\004\024" +
    "\141\001\002\000\004\005\ufff2\001\002\000\004\002\000" +
    "\001\002\000\004\025\014\001\002\000\004\004\145\001" +
    "\002\000\004\027\146\001\002\000\004\033\147\001\002" +
    "\000\004\027\150\001\002\000\004\004\151\001\002\000" +
    "\006\005\ufffd\032\004\001\002\000\004\005\ufffe\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\150\000\006\002\005\021\004\001\001\000\002\001" +
    "\001\000\006\003\010\007\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\141\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\004\027\005" +
    "\026\006\023\011\031\015\033\017\017\020\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\004\075\005\026\006\023\011\031\015" +
    "\033\017\017\020\020\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\012\041\013\040\014\036\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\012\053\013\040\014" +
    "\036\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\013\052\014\036\001\001\000\006\013" +
    "\045\014\036\001\001\000\002\001\001\000\004\014\051" +
    "\001\001\000\004\014\050\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\060\001\001\000\002\001\001\000\012\012\063\013\040" +
    "\014\036\016\062\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\012\065\013\040\014\036\001\001\000\002" +
    "\001\001\000\004\011\067\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\004\072\005\026\006\023\011\031" +
    "\015\033\017\017\020\020\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\004\077\005\026\006\023\011\031\015\033\017\017\020" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\012\063\013\040\014\036\016\103\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\012\063\013\040\014\036\016\113" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\004" +
    "\116\005\026\006\023\011\031\015\033\017\017\020\020" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\012" +
    "\063\013\040\014\036\016\121\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\004\124\005\026\006\023\011" +
    "\031\015\033\017\017\020\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\004\130\005" +
    "\026\006\023\011\031\015\033\017\017\020\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\133\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\021\151\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    
    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // FOR_SENTENCIA ::= For Parentesis_a T_dato ASIGNACION P_coma EXPRESION_BOOLEANA P_coma ASIGNACION Parentesis_c Llave_a CUERPO Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FOR_SENTENCIA",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-11)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // WHILE_SENTENCIA ::= Do Llave_a CUERPO Llave_c While Parentesis_a EXPRESION_BOOLEANA Parentesis_c P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("WHILE_SENTENCIA",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // WHILE_SENTENCIA ::= While Parentesis_a EXPRESION_BOOLEANA Parentesis_c Llave_a CUERPO Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("WHILE_SENTENCIA",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // EXPRESION_BOOLEANA ::= EXPRESION Op_relacional EXPRESION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION_BOOLEANA",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // IF_SENTENCIA ::= If Parentesis_a EXPRESION_BOOLEANA Parentesis_c Llave_a CUERPO Llave_c Else Llave_a CUERPO Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-10)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // IF_SENTENCIA ::= If Parentesis_a EXPRESION_BOOLEANA Parentesis_c Llave_a CUERPO Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("IF_SENTENCIA",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // FACTOR ::= Parentesis_a EXPRESION Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // FACTOR ::= Numero 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // FACTOR ::= Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FACTOR",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // TERMINO ::= FACTOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // TERMINO ::= TERMINO Division FACTOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // TERMINO ::= TERMINO Multiplicacion FACTOR 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("TERMINO",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EXPRESION ::= TERMINO 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // EXPRESION ::= EXPRESION Resta TERMINO 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // EXPRESION ::= EXPRESION Suma TERMINO 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("EXPRESION",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ASIGNACION ::= Identificador Igual EXPRESION 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ASIGNACION",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // PARAMETRO ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PARAMETRO",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // PARAMETRO ::= T_dato Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PARAMETRO",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // FUNCION ::= T_dato Identificador Parentesis_a PARAMETRO Parentesis_c Llave_a Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("FUNCION",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // DECLARACION_VAR ::= T_dato Identificador Igual Numero 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION_VAR",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DECLARACION_VAR ::= T_dato Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("DECLARACION_VAR",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= FOR_SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= WHILE_SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= IF_SENTENCIA 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= ASIGNACION P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= DECLARACION_VAR P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("SENTENCIA",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // CUERPO ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CUERPO",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // CUERPO ::= SENTENCIA CUERPO 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("CUERPO",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // MAIN_FUNC ::= T_dato Main Parentesis_a Parentesis_c Llave_a CUERPO Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("MAIN_FUNC",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTA_INCLUDES ::= 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_INCLUDES",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTA_INCLUDES ::= Numeral Include Comillas Identificador Punto Identificador Comillas LISTA_INCLUDES 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("LISTA_INCLUDES",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROGRAMA ::= LISTA_INCLUDES MAIN_FUNC 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PROGRAMA",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // PROGRAMA ::= LISTA_INCLUDES FUNCION MAIN_FUNC 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("PROGRAMA",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= PROGRAMA EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

