
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 05 10:18:55 GMT-06:00 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 5;
  public static final int Parentesis_c = 16;
  public static final int For = 8;
  public static final int Parentesis_a = 15;
  public static final int Suma = 10;
  public static final int Numero = 22;
  public static final int Identificador = 21;
  public static final int Comillas = 2;
  public static final int Llave_c = 18;
  public static final int Llave_a = 17;
  public static final int Numeral = 24;
  public static final int Op_relacional = 14;
  public static final int P_coma = 20;
  public static final int T_dato = 3;
  public static final int Main = 19;
  public static final int Include = 23;
  public static final int EOF = 0;
  public static final int Division = 13;
  public static final int Resta = 11;
  public static final int If = 4;
  public static final int error = 1;
  public static final int Op_logico = 27;
  public static final int Punto = 25;
  public static final int Modulo = 26;
  public static final int Do = 6;
  public static final int Igual = 9;
  public static final int While = 7;
  public static final int Multiplicacion = 12;
}

